import Head from "next/head";
import Link from "next/link";
import styles from "@/styles/Home.module.scss";

export default function Home() {
  return (
    <>
      <Head>
        <title>Esercitazioni Gennaio Roberto - POKEDEX</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script
          type="text/javascript"
          src="https://www.gstatic.com/charts/loader.js"
        ></script>
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>Esercitazioni Gennaio - Roberto - Pokedex</p>
          <div>
            <h1>Welcome to the Homepage</h1>
            <nav>
              <ul>
                <li>
                  <Link href="/pokedex/1">Pokedex</Link>
                </li>
                <li>
                  <Link href="/learn">How it works?</Link>
                </li>
                <li>
                  <Link href="/copyright">Copyright</Link>
                </li>
                <li>
                  <Link href="/about">About</Link>
                </li>
                <li>
                  <Link href="/contacts">Contacts</Link>
                </li>
              </ul>
            </nav>
          </div>
        </div>
      </main>
    </>
  );
}
